this.useSonar();
        if(this.isThereAWay()){
            this.goForward();
        }
        this.useSonar();
        if(this.isThereAWay()){
            this.goForward();
        }
        this.useSonar();
        if(this.isThereAWay()){
            this.goForward();
        }
        this.useSonar();
        console.table(this.robotMap)